services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
